# Generated by Django 3.2.9 on 2021-11-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='img',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
